# Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deploy
  namespace: default
  annotations:
    kubernetes.io/change-cause: "Update nginx 1.17.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: dev
  revisionHistoryLimit: 14
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3-alpine
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: nginx-cm
                  key: message
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: secret-message
          ports:
            - containerPort: 80

---
# ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-cm
  namespace: default
data:
  message: "HelloWorld"

---
# Secret
kind: Secret
apiVersion: v1
metadata:
  name: nginx-secret
  namespace: default
data:
  # generated by "echo HelloWorld | base64"
  secret-message: "SGVsbG9Xb3JsZAo="
